language: node_js
os:
  - linux
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  yarn: true
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - node
stages:
  - name: lint
  - test
  - name: deploy
matrix:
  allow_failures: []
  fast_finish: true

jobs:
  include:
    - stage: lint
      script:
        - yarn lint:types
        - yarn lint
    - stage: test
      script:
        - yarn test
    - stage: deploy
      script:
        - yarn build
      deploy:
        provider: npm
        email: '$npm_email'
        api_key: '$npm_key'
        skip_cleanup: true

branches:
  only:
    - master
